### ISSUE TITLE
[WF] Improve BuildForecast

### ISSUE THREAD

**Issue by joskuijpers** [theSeb1979/FS17_seasons#22] opened 2016-11-08 17:56 UTC
So what is next? What task can I do?

@theSeb1979 what are you working on now? Could you assign that issue to yourself?

**Comment by theSeb1979** [comment] 2016-11-08 18:01
Just cleaning up some code as I am going through. I just realised that there is a bug in the BuildForecast function. I wasn't thinking straight when I wrote it and I start the forecast from today, when ,actually, the forecast should be from tomorrow. You could edit this issue to that and and fix the problem. I am done with coding for the day. I am going to start looking at creating projects/milestones/tasks

**Comment by theSeb1979** [comment] 2016-11-08 18:02
table: 0x023f14e568e8 {
  [1] => table: 0x023f14e568e8 {
           [weekDay] => "Monday"
           [highTemp] => 21
           [lowTemp] => 14
           [weatherState] => "sun"
         }
  [2] => table: 0x023f14e568e8 {
           [weekDay] => "Tuesday"
           [highTemp] => 27
           [lowTemp] => 4
           [weatherState] => "sun"
         }
  [3] => table: 0x023f14e568e8 {
           [weekDay] => "Wednesday"
           [highTemp] => 25
           [lowTemp] => 6
           [weatherState] => "sun"
         }
  [4] => table: 0x023f14e568e8 {
           [weekDay] => "Thursday"
           [highTemp] => 15
           [lowTemp] => 9
           [weatherState] => "fog"
         }
  [5] => table: 0x023f14e568e8 {
           [weekDay] => "Friday"
           [highTemp] => 22
           [lowTemp] => 3
           [weatherState] => "sun"
         }
  [6] => table: 0x023f14e568e8 {
           [weekDay] => "Saturday"
           [highTemp] => 23
           [lowTemp] => 1
           [weatherState] => "sun"
         }
  [7] => table: 0x023f14e568e8 {
           [weekDay] => "Sunday"
           [highTemp] => 16
           [lowTemp] => 10
           [weatherState] => "cloudy"
         }
}

You can see what I mean in this table. The first forecast should be for Tuesday and the last forecast should be Monday.

**Comment by joskuijpers** [comment] 2016-11-08 18:09
Euhm i think BuildForecast totally breaks on day 2...

the days supplied to the seasonsUtil functions are 1+ (not 1-7).
You use the value from environment.currentDay (a weekday) and put it in the SeasonsUtil. That means you get the same forecast every week.

**Comment by theSeb1979** [comment] 2016-11-08 18:12
g_currentMission.environment.currentDay returns the actual current day from the game, which increases at midnight. I've been hard coding currentDay all over the place purely for testing, except for in this function. I am fairly sure the BuildForecast works, but can test it again. But to test it in its current implementation ,you have to fast forward time in the game.

**Comment by ian898** [comment] 2016-11-08 18:14
I can confirm g_currentMission.environment.currentDay returns the amount of game days played and never resets.

**Comment by joskuijpers** [comment] 2016-11-08 18:14
Alright, I was confused

**Comment by joskuijpers** [comment] 2016-11-08 18:18
Okay fixed it, just startDay = currentDay +1.
However, the table is never emptied...

**Comment by ian898** [comment] 2016-11-08 18:22
I get confused really easy so join the club especially when I get tired but I can never bring myself to walk away and come back to solve problem because it just plays on my mind haha

**Comment by theSeb1979** [comment] 2016-11-08 18:30
Good point on the table. It should be reset when it's rebuilt. We will need to figure out when the game changes the day in a nice way. 

However, I can't get SeasonsUtil:dayName to work and I don't think it's because of my changes to CalculateDayofWeekBasedOnDayNumber because I reverted them and I have the same issue.

Error: Running LUA method 'draw'.
C:/Users/sebastianp/Documents/My Games/FarmingSimulator2017/mods/FS17_seasons/seasonsUtil.lua:77: attempt to call method 'dayOfWeek' (a nil value)

**Comment by joskuijpers** [comment] 2016-11-08 18:32
Already fixed that on my side.
Was due to merge conflict.

**Comment by theSeb1979** [comment] 2016-11-08 18:33
Yeah,  I don't have a dayofweek function 👯

**Comment by joskuijpers** [comment] 2016-11-08 18:35
It is the Calculate function. Missed it when fixing the merge conflict on my end. All should work in the latest commit tho.

**Comment by joskuijpers** [comment] 2016-11-08 18:37
Okay confirmed it, at 00:00 it calculates a new forecast.
Ofcourse, the forecase is completely wrong so something needs to be done about that.

**Comment by joskuijpers** [comment] 2016-11-08 18:39
If the weatherForecast keeps with storm/rain/etc and showing the 7 day forecast in-game, i'll make a module that attempts to change ingame stuff depending on the day of the year.

I have no clue about the values of the fruits yet, so someone else should do that :P

**Comment by theSeb1979** [comment] 2016-11-08 18:40
Got you. Tested and dayOfWeek is now working. What do you mean by the forecast being wrong? When I was testing it was matching the environment rains, and temperature tables.

**Comment by joskuijpers** [comment] 2016-11-08 18:41
Well it says 'sun' but at 12PM it got really really cloudy in my game :P and before the day was over it got sunny again.

**Comment by theSeb1979** [comment] 2016-11-08 18:42
Interesting. I'll have to investigate this.

**Comment by joskuijpers** [comment] 2016-11-08 18:43
try using g_currentMission.missionInfo.timeScale = 1000;

**Comment by joskuijpers** [comment] 2016-11-08 18:56
Can someone verify that the new dayOfWeek still works the same?
Day 1 => monday (1 - 1 = 0, % 7 = 0, +1 = 1, thus monday in the array)
Day 8 => monday (8 - 1 = 7, % 7 = 0, +1 = 1 thus monday)
Day 9 => tuesday (9 - 1 = 8, % 7 = 1, +1 = 2)

**Comment by theSeb1979** [comment] 2016-11-08 18:57
On the subject of improving the forecast, since update(dt) is called every frame, I think this code

`-- FIXME(jos): is this the best solution? How about weather over a long period of time, like, one season? Or a year?
    local today = g_currentMission.SeasonsUtil:currentDayNumber();
    if (self.lastForecastPrediction < today) then
        self:buildForecast();
        self.lastForecastPrediction = today;
    end;`

should be in updateTick() which is called less frequently (every 30 ms if memory serves). That will be better, but if anybody has a more elegant solution for this, I am all ears. 

> Can someone verify that the new dayOfWeek still works the same?

Let me test it .

 me test it.

**Comment by joskuijpers** [comment] 2016-11-08 18:59
Could you try that updateTick? I never used it

**Comment by ian898** [comment] 2016-11-08 18:59
http://cbmoddingteam.weebly.com/fs17-time-manager.html this mod I created for testing my livestock manager its similar to fastforward but you just have to press once will skip current day in 12000x timescale. :)

**Comment by ian898** [comment] 2016-11-08 19:00
What actually is the updateTick I have asked around about that function and know one seems to know the actual answer when its is best implemented.

**Comment by joskuijpers** [comment] 2016-11-08 19:07
"Update is called every frame, while updateTick is only called for every network tick"
https://gdn.giants-software.com/thread.php?categoryId=3&threadId=1638
"In updateTick you should do stuff that is required for a prober network synchronization, e.g. calculating which states have changed.
On the other hand you should calculate things in the update function, which are required to be updated every frame. E.g. an animation of an object."

So yes, state changes should be in updateTick

**Comment by theSeb1979** [comment] 2016-11-08 19:07
> Stefan Geiger - GIANTS Software	06.12.2013 11:51
> Update is called every frame, while updateTick is only called for every network tick. At the moment the network tick rate is 30ms. In updateTick you should do stuff that is required for a prober network synchronization, e.g. calculating which states have changed.
> On the other hand you should calculate things in the update function, which are required to be updated every frame. E.g. an animation of an object.

Although I read elsewhere that updateTick was 45 ms, so I think it changes from version to version how often it's called, but I think it's called often enough for the purposes of the mod. 

Cheers, Ian. I'll check that out. 

I have moved the code into updateTick and I am going to call it a night to spend some time with my wife.

**Comment by joskuijpers** [comment] 2016-11-08 19:09
Haha we found the same source

**Comment by theSeb1979** [comment] 2016-11-08 19:17
You beat me by seconds. I had actually read that last night and I was trying to find it again. Once I had found it I was posting it, no matter what. :D

**Comment by ian898** [comment] 2016-11-08 19:35
Haha right that clears that up nicely thanks guys, I second that Seb mines feeling a little neglected haha, she lost me for a few days while I was doing Livestock Manager haha so she is worried this might be the next project haha

**Comment by theSeb1979** [comment] 2016-11-09 08:22
Working on possible bug. 

> Well it says 'sun' but at 12PM it got really really cloudy in my game :P and before the day was over it got sunny again.

**Comment by reallogger** [comment] 2016-11-09 18:59
I wonder if you guys are interested in a weather model based on actual weather data? Same as for the daylight I can supply a python script for how weather and forecast can be sampled. Wish I knew Lua better so I could supply the code directly.

**Comment by joskuijpers** [comment] 2016-11-09 20:06
I think that if you could supply some model that gives us temperatures depending on the day of year (min and max temperatures).
I figured it heavily depends on the day/night cycle: if it is light for 18 hours the sun has more time to warm the earth. So if you have an algorithm that matches the one you gave me… :D:D:D

Python is fine, I’ll convert it to LUA ;)

**Comment by reallogger** [comment] 2016-11-09 21:03
This scripts will be a little bit longer, but I'll capture the variation in temp difference with respect to seasons. Also taking into account longer days in summer and longer nights in winter. The plot linked below shows this effect. 

[https://puu.sh/scKZf.jpg](url)

I suggest to add some randomness in the model so every year will not be the same. 

First I will sample a monthly mean temperature from the figure linked below. It will be in the form of simple mathematical expressions, so no fancy functions to be used. [https://puu.sh/scM5Z.jpg](url)

This means there might be warm summers and colder summers. The two plots linked above are based on 15 years of tempterature data from the city of Yeovilton in the UK. 

Next step will be to sample the actual daily average temperature. The weather in each day will be independent from the previous day. This is not entirely correct, but since we have 7 day seasons I think it can be fine. From the daily average temperature, the daily max and min temperature will be randomly sampled. 

When it comes to the calculation done at midnight I am thinking the following. 
- The new day (at the end of the forecast) is sampled as above. 
- The weather for the upcoming days should be dependent on the forecast, but here also it would be nice to add some error.

**Comment by joskuijpers** [comment] 2016-11-09 21:12
Hmm, I think we want a summer to be more like 23-26 degrees, and a winter to be -8 - 5 degrees?
10 in summer seems way too low to me

**Comment by reallogger** [comment] 2016-11-09 21:48
Yes we will have summers with even above 26 degrees and some winter days with below -5. The lower figure (had to google how to include the images in the post...) shows the monthly means. The upper figure is the Mean Daily Maximum Temperature. So for January for instance the mean off the maximum temperature during all days in January in the period 2000-2015. As this are all mean curves we will have days that extend beyond those curves. We can adjust the model later on as well.

**Comment by joskuijpers** [comment] 2016-11-09 22:06
Regarding pictures: You can just copy a picture and Paste in in the github comment window ;)

**Comment by reallogger** [comment] 2016-11-09 22:09
doh... :) Thanks!

**Comment by reallogger** [comment] 2016-11-09 23:58
Will call it a day as well. Here you can see three different summer seasons (taken as the month of July here)  where the maximum temperature for each day during the season is displayed. 

![image](https://cloud.githubusercontent.com/assets/15114342/20159310/2107cdae-a6e0-11e6-9ac2-e3930d02955f.png)

As you can see there is more variation from day to day, than between seasons. Decreasing the variations from day to day results in something like this:

![image](https://cloud.githubusercontent.com/assets/15114342/20159357/6cae13c6-a6e0-11e6-81bc-73a977b19b50.png)

The lower figure is basically showing the data as it is.

**Comment by theSeb1979** [comment] 2016-11-10 10:33
Looks like the somehow the forecast is one day ahead behind of the actual forecast. For example rain in 6 shows up as rain in day 7. Not sure how that's happened, because I am sure it wasn't happening before. Working on it.

**Comment by reallogger** [comment] 2016-11-10 10:51
@theSeb1979 how is occurrence of rain established today? From the g_CurrentMission I see
there are several variables, like rainTypes, rains, lastRainScale, minRainDuration. 

I have data to come up with a probability of rain dependent on month and temperature. Rains more in winter and rain comes with low pressure and lower temps. Easy to capture, but would be nice if one of you could provide info on what variables you need. Or give me a hint to where I can read and study this myself. 

For instance is g_currentMission.environment.rains a table with days and a binary whether it will rain that day or not? How many rainTypes  exist?

**Comment by joskuijpers** [comment] 2016-11-10 10:56
There is also rainFadeCurve but might not need to change that.

Every rain in ‘rains’ has a startDay, endDatTime, endDay, startDayTime, rainType (fog, cloudy, rain, hail) and a duration. (Duration is end-start obviously).
So I think that if we want to control the weather, we need to generate this data ourselves (for today + coming 6 days, to incorporate in the weather forecast).

**Comment by reallogger** [comment] 2016-11-10 11:10
Thanks. No problem to generate that data. 

startDay and endDay is for rain that extends more than 1 day?

For rainType I assume there can be be a combination? Cloudy + rain for instance. Or does rain already incorporate the cloud cover?

**Comment by theSeb1979** [comment] 2016-11-10 11:26
@reallogger , I have printed out the rains table . you can check it out https://github.com/theSeb1979/FS17_seasons/blob/master/docs/environment_rains.txt

Update on this: multiple bugs that came out when the change was made to update the forecast at midnight. Still working on it.

**Comment by joskuijpers** [comment] 2016-11-10 11:26
Yeah, you can extend it multiple days. Normally this can be the same day. Or you can have it rain in the night by having startDay = 5, startTime = 8PM, and endTime = 6AM endDate = 6.
The specifics I can do ;)

It would be awesome if we can have a lot of cloudiness in the winter (like, almost all the time), with hail in-between. And maybe a small percentage time sun :P It has to feel like you can’t do work on the land and you really should give your animals a hug :D
This should be midwinter though (due to winter crops)

It already incorporates the cloud cover. I am not sure we can add snow ourselves. I think the engine just takes the value there and shows rain(+clouds), clouds, hail(+clouds), sun

**Comment by reallogger** [comment] 2016-11-10 12:02
Thanks both of you. Clarifies how I can crunch the numbers. :)

Yes, we should clearly have more rain in autumn and winter. We can reserve hail for the winter season so the visual impression of bad weather will be greater. In the summer there will be more like showers. Is it possible to have two rain events the same day? Rain in the morning and the afternoon?

**Comment by theSeb1979** [comment] 2016-11-10 12:03
Please move the weather manipulation discussion over to other issue

https://github.com/theSeb1979/FS17_seasons/issues/6

This was related to the bugs in buildForecast, which I have now fixed and tested. Closing this issue

**Closed by theSeb1979** 2016-11-10 12:03 UTC
Labels: bug, p_high
